import { User, UserRole } from "../../domain/entity/user.entity.js";
import { CreateUserDTO, UserResponseDTO } from "../dto/user.dto.js";
import { IUserRepository } from "../interface/user.repository.interface.js";
import { UserMapper } from "../mapping/user.mapper.js";

export class CreateUserUseCase {
  constructor(private userRepository: IUserRepository) {}

  public async execute(data: CreateUserDTO): Promise<UserResponseDTO | null> {
    const existing = await this.userRepository.findByEmail(data.email);
    if (existing) {
      throw new Error("User already exists");
    }

    const newUser = new User(
      "", // id will be generated by repository or database
      data.name,
      data.email,
      data.role,
      data.password
    );

    const savedUser = await this.userRepository.save(newUser);
    return savedUser ? UserMapper.toResponseDTO(savedUser) : null;
  }
}

export class GetAllUsersUseCase {
  constructor(private userRepository: IUserRepository) {}

  public async execute(): Promise<UserResponseDTO[]> {
    const users = await this.userRepository.findAll();
    return UserMapper.toResponseDTOList(users);
  }
}

export class DeleteUserUseCase {
  constructor(private userRepository: IUserRepository) {}

  public async execute(id: string): Promise<boolean> {
    return await this.userRepository.delete(id);
  }
}
